In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import re
import string
import nltk
pd.set_option('display.max_colwidth', 100)


In [2]:

dataset=pd.read_csv(r"F:\Tutorials\Certified program in MACHINE LEARNING and ARTIFICIAL INTELLIGENCE\Assignments\assignment_7\spam.csv")
dataset.head()

v1  \
0   ham   
1   ham   
2  spam   
3   ham   
4   ham   

                                                                                                    v2  \
0  Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there g...   
1                                                                        Ok lar... Joking wif u oni...   
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive ...   
3                                                    U dun say so early hor... U c already then say...   
4                                        Nah I don't think he goes to usf, he lives around here though   

  Unnamed: 2 Unnamed: 3 Unnamed: 4  
0        NaN        NaN        NaN  
1        NaN        NaN        NaN  
2        NaN        NaN        NaN  
3        NaN        NaN        NaN  
4        NaN        NaN        NaN

In [3]:
data=dataset[dataset.columns[0:2]]
data.head()

v1  \
0   ham   
1   ham   
2  spam   
3   ham   
4   ham   

                                                                                                    v2  
0  Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there g...  
1                                                                        Ok lar... Joking wif u oni...  
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive ...  
3                                                    U dun say so early hor... U c already then say...  
4                                        Nah I don't think he goes to usf, he lives around here though

In [4]:
data.columns=['label','body_text']
data.head()

label  \
0   ham   
1   ham   
2  spam   
3   ham   
4   ham   

                                                                                             body_text  
0  Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there g...  
1                                                                        Ok lar... Joking wif u oni...  
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive ...  
3                                                    U dun say so early hor... U c already then say...  
4                                        Nah I don't think he goes to usf, he lives around here though

In [5]:
df=data
df['label'] = df.label.map({'ham':0, 'spam':1})
print(df.shape)
df.head()

(5572, 2)


<ipython-input-5-b3dab5ed723e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = df.label.map({'ham':0, 'spam':1})


label  \
0      0   
1      0   
2      1   
3      0   
4      0   

                                                                                             body_text  
0  Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there g...  
1                                                                        Ok lar... Joking wif u oni...  
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive ...  
3                                                    U dun say so early hor... U c already then say...  
4                                        Nah I don't think he goes to usf, he lives around here though

In [6]:
stopwords = nltk.corpus.stopwords.words('english')
ps = nltk.PorterStemmer()


In [7]:
def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation]) # remove puctuation
    tokens = re.split('\W+', text)                                                    # tokenize
    text = [ps.stem(word) for word in tokens if word not in stopwords]                #remove stopwords, stemming
    
    return text

In [8]:
from sklearn.feature_extraction.text import CountVectorizer                         # BOW using countvector

count_vect = CountVectorizer(analyzer=clean_text)
X_counts = count_vect.fit_transform(data['body_text'])
print(X_counts.shape)
#print(count_vect.get_feature_names())
print(count_vect.get_feature_names_out())

(5572, 8005)
['' '0' '008704050406' ... 'zoom' 'zouk' 'zyada']


In [10]:
X_counts_df = pd.DataFrame(X_counts.toarray())
X_counts_df.columns = count_vect.get_feature_names()
X_counts_df

C:\Users\vishn\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


0  008704050406  0089mi  0121  01223585236  01223585334  0125698789  \
0     0  0             0       0     0            0            0           0   
1     0  0             0       0     0            0            0           0   
2     0  0             0       0     0            0            0           0   
3     0  0             0       0     0            0            0           0   
4     0  0             0       0     0            0            0           0   
...  .. ..           ...     ...   ...          ...          ...         ...   
5567  0  0             0       0     0            0            0           0   
5568  0  0             0       0     0            0            0           0   
5569  0  0             0       0     0            0            0           0   
5570  0  0             0       0     0            0            0           0   
5571  0  0             0       0     0            0            0           0   

      02  020603  ...  zebra  zed  zero  zhong  zindgi  zoe  zogtoriu  zoom  \
0      0       0  ...      0    0     0      0       0    0         0     0   
1      0       0  ...      0    0     0      0       0    0         0     0   
2      0       0  ...      0    0     0      0       0    0         0     0   
3      0       0  ...      0    0     0      0       0    0         0     0   
4      0       0  ...      0    0     0      0       0    0         0     0   
...   ..     ...  ...    ...  ...   ...    ...     ...  ...       ...   ...   
5567   0       0  ...      0    0     0      0       0    0         0     0   
5568   0       0  ...      0    0     0      0       0    0         0     0   
5569   0       0  ...      0    0     0      0       0    0         0     0   
5570   0       0  ...      0    0     0      0       0    0         0     0   
5571   0       0  ...      0    0     0      0       0    0         0     0   

      zouk  zyada  
0        0      0  
1        0      0  
2        0      0  
3        0      0  
4        0      0  
...    ...    ...  
5567     0      0  
5568     0      0  
5569     0      0  
5570     0      0  
5571     0      0  

[5572 rows x 8005 columns]

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['body_text'], 
                                                    df['label'], 
                                                    random_state=42,
                                                    test_size=0.3)

print('Total no. of data points: {}'.format(df.shape[0]))
print('No. of data points in training dataset: {}'.format(X_train.shape[0]))
print('No. of data points in testing dataset: {}'.format(X_test.shape[0]))

Total no. of data points: 5572
No. of data points in training dataset: 3900
No. of data points in testing dataset: 1672


In [13]:
count_vector = CountVectorizer(analyzer=clean_text)

training_data = (count_vector.fit_transform(X_train)).toarray()
print(training_data)
print(training_data.shape)

testing_data = (count_vector.transform(X_test)).toarray()
print(testing_data)
print(testing_data.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3900, 6562)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(1672, 6562)


In [14]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=200)
RF.fit(training_data, y_train)

RandomForestClassifier(n_estimators=200)

In [15]:
y_RF = RF.predict(testing_data)

In [17]:

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print('Accuracy score :' , format(accuracy_score(y_test, y_RF)))
print('Precision score:', format(precision_score(y_test,y_RF)))
print('Recall score:', format(recall_score(y_test, y_RF)))
print('F1 score:', format(f1_score(y_test, y_RF)))
print('\n\n')

Accuracy score : 0.972488038277512
Precision score: 1.0
Recall score: 0.7899543378995434
F1 score: 0.8826530612244898



